# Generated by Django 5.1.3 on 2025-05-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_name', models.CharField(max_length=20, unique=True, verbose_name='Age range')),
                ('min_age', models.PositiveIntegerField(verbose_name='Minimum age')),
                ('max_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum age')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Age Range',
                'verbose_name_plural': 'Age Ranges',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('verification_code', models.CharField(max_length=6, verbose_name='Verification code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Attempts')),
            ],
            options={
                'verbose_name': 'SMS Verification',
                'verbose_name_plural': 'SMS Verifications',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Type code')),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='age_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.agerange', verbose_name='Age range'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_types',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.usertype', verbose_name='User types'),
        ),
    ]
