# Generated by Django 5.1.3 on 2025-05-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agerange_smsverification_usertype_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverification',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Account locked until'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed login attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last login IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('facebook', 'Facebook'), ('google', 'Google'), ('apple', 'Apple')], default='phone', max_length=20, verbose_name='Login method'),
        ),
    ]
